---
- name: Install NGINX
  ansible.builtin.include_role:
    name: nginx

- name: Ensure group "www-data" exists
  ansible.builtin.group:
    name: www-data
    state: present

- name: Ensure user "www-data" exists
  user:
    name: www-data
    group: www-data
    create_home: false
    shell: /bin/false
    state: present

- name: Add the user "nginx" to www-data group
  ansible.builtin.user:
    name: nginx
    groups: www-data
    append: true

- name: Create web root owned by "www-data"
  ansible.builtin.file:
    path: /var/www
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"

- name: Generate web root content from variable
  copy:
    content: "{{ index_content }}"
    dest: /var/www/index.html
    user: www-data
    group: www-data

- name: Configure base NGINX
  ansible.builtin.include_role:
    name: nginx_config

- name: Copy nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"

- name: Copy conf.d/default.conf
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: "0644"

- name: Nginx started and enabled
  service:
    name: nginx
    state: started
    enabled: yes

- name: Allow HTTP connection from load balancers
  community.general.ufw:
    rule: allow
    proto: tcp
    src: "{{ hostvars.loadbalancer.ansible_host }}"
    port: "80"